CREATE TABLE IF NOT EXISTS `movie_quote` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quote` VARCHAR(200) NOT NULL,
  `source` VARCHAR(50) NOT NULL,
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
