{
 "title": "Movie quote service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Heap memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{kubernetes_name=\"movie-quote-service\", area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(http_server_requests_seconds_count{kubernetes_name=\"movie-quote-service\", status=\"200\"}[2m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_uptime_seconds{kubernetes_name=\"movie-quote-service\"}"
    }
   ]
  }
 ]
}